# Generated by Django 5.0.7 on 2026-03-27 23:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('exams', '0001_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('letter_grade', models.CharField(help_text='Letter grade (A, B+, B, C+, C, D, F)', max_length=2)),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('grade_points', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)])),
                ('description', models.CharField(help_text='Description (Excellent, Very Good, etc.)', max_length=50)),
            ],
            options={
                'verbose_name': 'Grade Scale',
                'verbose_name_plural': 'Grade Scales',
                'ordering': ['-min_percentage'],
            },
        ),
        migrations.CreateModel(
            name='GraduatingStudent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('final_cgpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('classification', models.CharField(choices=[('FIRST_CLASS', 'First Class Honours'), ('SECOND_UPPER', 'Second Class Honours (Upper Division)'), ('SECOND_LOWER', 'Second Class Honours (Lower Division)'), ('THIRD_CLASS', 'Third Class Honours'), ('PASS', 'Pass')], max_length=20)),
                ('total_credits', models.IntegerField()),
                ('is_cleared', models.BooleanField(default=False, help_text='Cleared for graduation (no outstanding fees/issues)')),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Graduating Student',
                'verbose_name_plural': 'Graduating Students',
                'ordering': ['-final_cgpa', 'student'],
            },
        ),
        migrations.CreateModel(
            name='GraduationList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.CharField(max_length=9)),
                ('ceremony_date', models.DateField(blank=True, null=True)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Graduation List',
                'verbose_name_plural': 'Graduation Lists',
                'ordering': ['-academic_year', 'program'],
            },
        ),
        migrations.CreateModel(
            name='PromotionalList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('semester', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=9)),
                ('level', models.IntegerField(help_text='Current level (e.g., Year 1, 2, 3, 4)')),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('is_executed', models.BooleanField(db_index=True, default=False, help_text='Whether promotions have been applied')),
                ('executed_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Promotional List',
                'verbose_name_plural': 'Promotional Lists',
                'ordering': ['-academic_year', '-semester', 'program', 'level'],
            },
        ),
        migrations.CreateModel(
            name='ScriptCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('script_collected', models.BooleanField(default=False)),
                ('collection_date', models.DateTimeField(blank=True, null=True)),
                ('script_number', models.CharField(blank=True, help_text='Physical script identifier', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about missing scripts or issues', null=True)),
            ],
            options={
                'verbose_name': 'Script Collection',
                'verbose_name_plural': 'Script Collections',
                'ordering': ['-collection_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentPromotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('current_level', models.IntegerField()),
                ('next_level', models.IntegerField(blank=True, null=True)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('credits_earned', models.IntegerField()),
                ('status', models.CharField(choices=[('PROMOTED', 'Promoted'), ('PROBATION', 'On Probation'), ('REPEAT', 'Repeat Level'), ('WITHDRAWN', 'Withdrawn')], db_index=True, max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('effective_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Student Promotion',
                'verbose_name_plural': 'Student Promotions',
                'ordering': ['promotional_list', 'student'],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of students', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='invigilators',
            field=models.ManyToManyField(blank=True, related_name='invigilated_exams', to='staff.staffmember'),
        ),
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='venue',
            field=models.CharField(blank=True, help_text='Exam venue/location', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='approval_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='grade',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grade',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='grade_letter',
            field=models.CharField(blank=True, help_text='Letter grade (A, B+, B, C+, C, D, F)', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='grade',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grade',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['status'], name='exams_exam_status_7a27f8_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['approval_status'], name='exams_grade_approva_70dbc6_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['is_published'], name='exams_grade_is_publ_10d0a5_idx'),
        ),
        migrations.AddField(
            model_name='gradescale',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_scales', to='courses.program'),
        ),
        migrations.AddField(
            model_name='graduatingstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduations', to='students.student'),
        ),
        migrations.AddField(
            model_name='graduationlist',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_graduation_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='graduationlist',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_lists', to='courses.program'),
        ),
        migrations.AddField(
            model_name='graduatingstudent',
            name='graduation_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduating_students', to='exams.graduationlist'),
        ),
        migrations.AddField(
            model_name='promotionallist',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_promotional_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionallist',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotional_lists', to='courses.program'),
        ),
        migrations.AddField(
            model_name='scriptcollection',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_scripts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scriptcollection',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_collections', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='scriptcollection',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_collections', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentpromotion',
            name='promotional_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_promotions', to='exams.promotionallist'),
        ),
        migrations.AddField(
            model_name='studentpromotion',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='gradescale',
            index=models.Index(fields=['program', 'min_percentage', 'max_percentage'], name='exams_grade_program_6608df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gradescale',
            unique_together={('program', 'letter_grade')},
        ),
        migrations.AddIndex(
            model_name='graduationlist',
            index=models.Index(fields=['program', 'academic_year'], name='exams_gradu_program_203086_idx'),
        ),
        migrations.AddIndex(
            model_name='graduationlist',
            index=models.Index(fields=['is_approved'], name='exams_gradu_is_appr_0f30f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='graduationlist',
            unique_together={('academic_year', 'program')},
        ),
        migrations.AddIndex(
            model_name='graduatingstudent',
            index=models.Index(fields=['graduation_list', 'classification'], name='exams_gradu_graduat_40c093_idx'),
        ),
        migrations.AddIndex(
            model_name='graduatingstudent',
            index=models.Index(fields=['student', 'final_cgpa'], name='exams_gradu_student_44af37_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='graduatingstudent',
            unique_together={('graduation_list', 'student')},
        ),
        migrations.AddIndex(
            model_name='promotionallist',
            index=models.Index(fields=['program', 'level'], name='exams_promo_program_21ab88_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionallist',
            index=models.Index(fields=['academic_year', 'semester'], name='exams_promo_academi_18d6b0_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionallist',
            index=models.Index(fields=['is_approved', 'is_executed'], name='exams_promo_is_appr_98f03b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='promotionallist',
            unique_together={('semester', 'academic_year', 'program', 'level')},
        ),
        migrations.AddIndex(
            model_name='scriptcollection',
            index=models.Index(fields=['exam', 'student'], name='exams_scrip_exam_id_053292_idx'),
        ),
        migrations.AddIndex(
            model_name='scriptcollection',
            index=models.Index(fields=['exam', 'script_collected'], name='exams_scrip_exam_id_5e554b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scriptcollection',
            unique_together={('exam', 'student')},
        ),
        migrations.AddIndex(
            model_name='studentpromotion',
            index=models.Index(fields=['student', 'status'], name='exams_stude_student_d07d0d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentpromotion',
            index=models.Index(fields=['promotional_list', 'status'], name='exams_stude_promoti_c908b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentpromotion',
            unique_together={('promotional_list', 'student')},
        ),
    ]
