# Generated by Django 5.0.7 on 2026-03-27 23:18

from django.db import migrations


def populate_grade_scales(apps, schema_editor):
    """
    Populate default Sierra Leone grading system for all programs
    """
    GradeScale = apps.get_model('exams', 'GradeScale')
    Program = apps.get_model('courses', 'Program')

    # Default Sierra Leone grading system
    grade_scales = [
        {'letter_grade': 'A', 'min_percentage': 80.00, 'max_percentage': 100.00, 'grade_points': 4.00, 'description': 'Excellent'},
        {'letter_grade': 'B+', 'min_percentage': 75.00, 'max_percentage': 79.99, 'grade_points': 3.50, 'description': 'Very Good'},
        {'letter_grade': 'B', 'min_percentage': 70.00, 'max_percentage': 74.99, 'grade_points': 3.00, 'description': 'Good'},
        {'letter_grade': 'C+', 'min_percentage': 65.00, 'max_percentage': 69.99, 'grade_points': 2.50, 'description': 'Fairly Good'},
        {'letter_grade': 'C', 'min_percentage': 60.00, 'max_percentage': 64.99, 'grade_points': 2.00, 'description': 'Fair'},
        {'letter_grade': 'D', 'min_percentage': 50.00, 'max_percentage': 59.99, 'grade_points': 1.50, 'description': 'Pass'},
        {'letter_grade': 'F', 'min_percentage': 0.00, 'max_percentage': 49.99, 'grade_points': 0.00, 'description': 'Fail'},
    ]

    # Create grade scales for all existing programs
    for program in Program.objects.all():
        for scale in grade_scales:
            GradeScale.objects.get_or_create(
                program=program,
                letter_grade=scale['letter_grade'],
                defaults={
                    'min_percentage': scale['min_percentage'],
                    'max_percentage': scale['max_percentage'],
                    'grade_points': scale['grade_points'],
                    'description': scale['description'],
                }
            )


def reverse_populate_grade_scales(apps, schema_editor):
    """
    Remove all default grade scales
    """
    GradeScale = apps.get_model('exams', 'GradeScale')
    GradeScale.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_phase1_examination_enhancements'),
        ('courses', '__latest__'),  # Ensure courses app is migrated first
    ]

    operations = [
        migrations.RunPython(populate_grade_scales, reverse_populate_grade_scales),
    ]
