# Generated by Django 5.0.7 on 2026-03-28 09:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_populate_default_grade_scales'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['exam', 'is_deleted', 'approval_status'], name='exam_deleted_approval_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'is_published', '-graded_date'], name='student_published_date_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['exam', 'approval_status', 'is_published'], name='exam_approval_published_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['graded_by', '-graded_date'], name='grader_date_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['exam', 'is_deleted'], name='exam_deleted_idx'),
        ),
    ]
