# Generated by Django 5.0.7 on 2026-03-24 16:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0001_initial'),
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Template identifier name', max_length=200, unique=True)),
                ('template_type', models.CharField(choices=[('ADMISSION', 'Admission Notification'), ('PAYMENT', 'Payment Notification'), ('EXAM', 'Exam Notification'), ('GENERAL', 'General Notification'), ('REGISTRATION', 'Registration Notification'), ('RESULTS', 'Results Notification'), ('ALERT', 'Alert Notification')], db_index=True, max_length=20)),
                ('message', models.TextField(help_text='SMS message with placeholders like {student_name}, {amount}, {date}')),
                ('description', models.TextField(blank=True, help_text='Description of when to use this template', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('available_placeholders', models.JSONField(blank=True, default=list, help_text='List of available placeholders for this template')),
            ],
            options={
                'verbose_name': 'SMS Template',
                'verbose_name_plural': 'SMS Templates',
                'ordering': ['template_type', 'name'],
                'indexes': [models.Index(fields=['template_type'], name='communicati_templat_1a7083_idx'), models.Index(fields=['is_active'], name='communicati_is_acti_0e2bb1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('official_name', models.CharField(help_text='Full name of the official', max_length=200)),
                ('title', models.CharField(help_text='Official title (e.g., Registrar, Dean, Vice Chancellor)', max_length=200)),
                ('department', models.CharField(blank=True, help_text='Department or Office', max_length=200, null=True)),
                ('signature_image', models.ImageField(help_text='Scanned signature image', upload_to='signatures/')),
                ('is_default', models.BooleanField(default=False, help_text='Default signature for documents')),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(blank=True, help_text='Campus this signature belongs to (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='official_signatures', to='campuses.campus')),
            ],
            options={
                'verbose_name': 'Signature',
                'verbose_name_plural': 'Signatures',
                'ordering': ['official_name'],
                'indexes': [models.Index(fields=['is_default'], name='communicati_is_defa_f351c3_idx'), models.Index(fields=['is_active'], name='communicati_is_acti_2791a3_idx'), models.Index(fields=['campus'], name='communicati_campus__c5492b_idx')],
            },
        ),
    ]
